### ISSUE TITLE
Update the plugin to work with the next release (3.4.0)

### ISSUE THREAD

**Issue by jonasraoni** [pkp/customLocale#15]
The https://github.com/pkp/customLocale/pull/12 was slightly outdated when it was merged and requires minor updates to get into a working state.

PR
- https://github.com/pkp/customLocale/pull/16

**Comment by jonasraoni** [comment]
@asmecher I've added the PR to the top of the issue.

**Comment by asmecher** [comment]
Thanks, @jonasraoni, I've read through the code and it looks good -- a rewrite was probably necessary. Please get the tests working and then I'll give it a spin from a user standpoint.

**Comment by asmecher** [comment]
> Do you know if this plugin is used mostly to correct and fill missing translations? If yes, perhaps we can create another issue to integrate it with Weblate somehow (a direct link next to the locale key or at least a mention saying the best long-term solution is to update the information on weblate).

No, I think the most common use case is wording tweaks that the journal wants to make without modifying the .po files directly. And I'd rather we encourage Weblate as a direct path for missing translations, rather than mixing the two use cases into this plugin, which would probably lead to muddled submissions to Weblate.

**Comment by asmecher** [comment]
Merged; I think this is OK to close, thanks!
